# Copyright 2018 MaidSafe.net limited.
#
# This SAFE Network Software is licensed to you under The General Public License (GPL), version 3.
# Unless required by applicable law or agreed to in writing, the SAFE Network Software distributed
# under the GPL Licence is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. Please review the Licences for the specific language governing
# permissions and limitations relating to use of the SAFE Network Software.

[workspace]
members = ["safe_app", "safe_authenticator", "safe_authenticator_ffi", "safe_core", "tests"]

[patch.crates-io]
# safe-nd = { path = "../safe-nd"}
#safe-nd = { git = "https://github.com/maidsafe/safe-nd.git", ref = "d722f38" }
#safe-transfers = { git = "https://github.com/maidsafe/safe-transfers.git" }
# safe-transfers = { path="../safe-transfers" }

xor_name = { git="https://github.com/joshuef/xor-name.git", branch="AddRandom"}
